/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApiPreview: typeof import('./src/components/ApiPreview.vue')['default']
    ConfigSection: typeof import('./src/components/ConfigSection.vue')['default']
    OpenAPIEditor: typeof import('./src/components/OpenAPIEditor.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    ResultSection: typeof import('./src/components/ResultSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerConfig: typeof import('./src/components/ServerConfig.vue')['default']
    ServerStatus: typeof import('./src/components/ServerStatus.vue')['default']
  }
}
